### PR TITLE
revert removal of headers in session cache

### LINKED ISSUE #4: Can't compile (install) with Crystal 0.30
```
➤  shards build --release
Dependencies are satisfied
Building: arachnid
Error target arachnid failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/arachnid/session_cache.cr:67:20

 67 | headers: headers,
               ^------
Error: undefined local variable or method 'headers' for Arachnid::SessionCache
```

### PR DESCRIPTION
**Pull request by jkthorne**
fixes https://github.com/watzon/arachnid/issues/4

### CODE REVIEW

**Comment by jkthorne** [comment]
@watzon I was unable to build this after updating.  I added the headers back and it all compiled correctly.  I am unsure if I am using the session cache now though.

**Comment by watzon** [comment]
A lot of stuff is actually getting ready to change as I migrate Arachnid to using watzon/marionette to fetch content instead of using a normal HTTP client. It should allow me to fix a lot of issues like this too.

**Comment by jkthorne** [comment]
Sounds good.  Should this be closed or do you want to have it merged in during the migration.

**Comment by watzon** [comment]
I'll leave it for now so I don't forget to check

**Pull request closed without merging**
